name: "Create semver tag at current github ref using passed branch name as a suffix."
description: "Use the branch name passed (can be either refs/heads/name-of-thing or just name-of-thing)."
inputs:
  prerelease:
    description: "If set, looks for pre-release tag patterns (v1.1.1-${suffix}.${count})"
    default: ""
  prerelease_suffix:
    description: "If prerelease is set, this string is used as the ${suffix} in the tag pattern. (Default: beta)"
    default: "beta"
  latest_tag:
    description: "Lastest tag to bump from."
    default: ""
  last_release:
    description: "Last release tag"
    default: ""
  default_bump:
    description: "Bump version along by this. (Default: patch)"
    default: "patch"
  with_v:
    description: "New tag will start with a v prefix"
    default: ""
  caller_repo_subfolder:
    description: "Location to checkout active repository into. (Default: ./next-tag-caller-repository)"
    default: "./next-tag-caller-repository"
  commitish_a:
    description: "Commit used to look for version bump triggers in messages"
    required: true
  commitish_b:
    description: "Commit used to look for version bump triggers in messages"
    required: true

outputs:

  prerelease_suffix:
    description: "Inputed prerelease_suffix variable."
    value: ${{ inputs.prerelease_suffix }}
  latest_tag:
    description: "Inputed latest_tag variable."
    value: ${{inputs.latest_tag}}
  last_release:
    description: "Inputed last_release variable."
    value: ${{inputs.last_release}}
  with_v:
    description: "Inputed with_v variable."
    value: ${{inputs.with_v}}

  prerelease:
    description: "Calculated prerelease variable."
    value: ${{ steps.get_next_tag.outputs.prerelease_calculated }}
  next_tag:
    description: "Next tag that should be created."
    value: ${{steps.get_next_tag.outputs.next_tag}}
  commitish_a:
    description: "Commit used to look for version bump triggers in messages"
    value: ${{steps.get_next_tag.outputs.commitish_a}}
  commitish_b:
    description: "Commit used to look for version bump triggers in messages"
    value: ${{steps.get_next_tag.outputs.commitish_b}}
  majors:
    description: "number of #major found."
    value: ${{steps.get_next_tag.outputs.majors}}
  minors:
    description: "number of #minor found."
    value: ${{steps.get_next_tag.outputs.minors}}
  patches:
    description: "number of #patch found."
    value: ${{steps.get_next_tag.outputs.patches}}


runs:
  using: "composite"
  steps:
    - name: "Checkout original repo to set folder"
      uses: actions/checkout@v4
      env:
        FOLDER_PATH: ${{inputs.caller_repo_subfolder}}
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref}}
        path: ${FOLDER_PATH}
        fetch-tags: true
        fetch-depth: 0
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: GitPython
      shell: bash
      run: |
        pip3 install -q git+https://github.com//gitpython-developers/GitPython@44102f30eaadcd122899f5f801f28b83bd9a5111
    - name: natsort
      shell: bash
      run: |
        pip3 install -q git+https://github.com//SethMMorton/natsort@d9503c08f8f83ce8a89bfcc45fec136868756243
    - name: semver
      shell: bash
      run: |
        pip3 install -q git+https://github.com/python-semver/python-semver.git@ec9348aefd8e9f287f451fcf2e837621a40e3ca4
    - name: Get new Tag
      id: get_next_tag
      shell: bash
      env:
        ACTION_SRC_PATH: ${{ github.action_path }}
        TARGET_REPO: "${{github.workspace}}/${{inputs.caller_repo_subfolder}}"
        COMMITISH_A: ${{inputs.commitish_a}}
        COMMITISH_B: ${{inputs.commitish_b}}
        PRERELEASE: ${{inputs.prerelease}}
        PRERELEASE_SUFFIX: ${{inputs.prerelease_suffix}}
        LATEST_TAG: ${{inputs.latest_tag}}
        LAST_RELEASE: ${{inputs.last_release}}
        WITH_V: ${{inputs.with_v}}
        DEFAULT_BUMP: ${{inputs.default_bump}}
        # used by the python code directly
        github_pr_title: ${{ github.event.pull_request.title }}
        github_pr_body: ${{ github.event.pull_request.body }}
      run: |
        python ${ACTION_SRC_PATH}/./next-tag.py \
          --repository_root="${TARGET_REPO}" \
          --commitish_a="${COMMITISH_A}" \
          --commitish_b="${COMMITISH_B}" \
          --prerelease="${PRERELEASE}" \
          --prerelease_suffix="${PRERELEASE_SUFFIX}" \
          --latest_tag="${LATEST_TAG}" \
          --last_release="${LAST_RELEASE}" \
          --with_v="${WITH_V}" \
          --default_bump="${DEFAULT_BUMP}"
