name: "Determine the next semver tag to create"
description: "Determine the next semver tag to create"
inputs:
  prerelease:
    description: "If set, looks for pre-release tag patterns (v1.1.1-${suffix}.${count})"
    default: ""
  prerelease_suffix:
    description: "If prerelease is set, this string is used as the ${suffix} in the tag pattern. (Default: beta)"
    default: "beta"
  latest_tag:
    description: "Lastest tag to bump from."
    default: ""
  last_release:
    description: "Last release tag"
    default: ""
  default_bump:
    description: "Bump version along by this. (Default: patch)"
    default: "patch"
  with_v:
    description: "New tag will start with a v prefix"
    default: ""
  caller_repo_subfolder:
    description: "Location to checkout active repository into. (Default: ./next-tag-caller-repository)"
    default: "./next-tag-caller-repository"
  commitish_a:
    description: "Commit used to look for version bump triggers in messages"
    required: true
  commitish_b:
    description: "Commit used to look for version bump triggers in messages"
    required: true
  ## Used to capture the intial values before they get overwritten
  action_ref:
    description: "Capture the starting value of github.action_ref. DO NOT SET"
    default: ${{ github.action_ref }}
  action_repository:
    description: "Capture the starting value of github.action_repository. DO NOT SET"
    default: ${{ github.action_repository }}

outputs:
  prerelease_suffix:
    description: "Inputed prerelease_suffix variable."
    value: ${{ inputs.prerelease_suffix }}
  latest_tag:
    description: "Inputed latest_tag variable."
    value: ${{inputs.latest_tag}}
  last_release:
    description: "Inputed last_release variable."
    value: ${{inputs.last_release}}
  with_v:
    description: "Inputed with_v variable."
    value: ${{inputs.with_v}}

  prerelease:
    description: "Calculated prerelease variable."
    value: ${{ steps.get_next_tag.outputs.prerelease_calculated }}
  next_tag:
    description: "Next tag that should be created."
    value: ${{steps.get_next_tag.outputs.next_tag}}
  commitish_a:
    description: "Commit used to look for version bump triggers in messages"
    value: ${{steps.get_next_tag.outputs.commitish_a}}
  commitish_b:
    description: "Commit used to look for version bump triggers in messages"
    value: ${{steps.get_next_tag.outputs.commitish_b}}
  majors:
    description: "number of #major found."
    value: ${{steps.get_next_tag.outputs.majors}}
  minors:
    description: "number of #minor found."
    value: ${{steps.get_next_tag.outputs.minors}}
  patches:
    description: "number of #patch found."
    value: ${{steps.get_next_tag.outputs.patches}}


runs:
  using: "composite"
  steps:
    - name: "Checkout original repo to set folder"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref}}
        path: ${{inputs.caller_repo_subfolder}}
        fetch-tags: true
        fetch-depth: 0
    - name: "Checkout this actions repo into a subfolder at this version"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.action_repository }}
        ref: ${{ inputs.action_ref }}
        path: ./_ghnexttagaction
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: pip
      shell: bash
      env:
        PY_APP_DIR: "./_ghnexttagaction/python"
      run: |
        cd ${PY_APP_DIR}
        pip install -q -r ./requirements.txt
        pip install -e .
    - name: Get new Tag
      id: get_next_tag
      shell: bash
      env:
        PY_APP_DIR: "./_ghnexttagaction/python"
        TARGET_REPO: "${{github.workspace}}/${{inputs.caller_repo_subfolder}}"
        COMMITISH_A: ${{inputs.commitish_a}}
        COMMITISH_B: ${{inputs.commitish_b}}
        PRERELEASE: ${{inputs.prerelease}}
        PRERELEASE_SUFFIX: ${{inputs.prerelease_suffix}}
        LATEST_TAG: ${{inputs.latest_tag}}
        LAST_RELEASE: ${{inputs.last_release}}
        WITH_V: ${{inputs.with_v}}
        DEFAULT_BUMP: ${{inputs.default_bump}}
        # used by the python code directly
        github_pr_title: ${{ github.event.pull_request.title }}
        github_pr_body: ${{ github.event.pull_request.body }}
      run: |
        echo -e "# next-tag setup:"
        echo -e "PY_APP_DIR: ${PY_APP_DIR}"
        echo -e "TARGET_REPO: ${TARGET_REPO}"
        echo -e "COMMITISH_A: ${COMMITISH_A}"
        echo -e "COMMITISH_B: ${COMMITISH_B}"
        echo -e "PRERELEASE: ${PRERELEASE}"
        echo -e "PRERELEASE_SUFFIX: ${PRERELEASE_SUFFIX}"
        echo -e "LATEST_TAG: ${LATEST_TAG}"
        echo -e "LAST_RELEASE: ${LAST_RELEASE}"
        echo -e "WITH_V: ${WITH_V}"
        echo -e "DEFAULT_BUMP: ${DEFAULT_BUMP}"

         cd ${PY_APP_DIR}
        python ./actions/commands/next_tag.py \
          --repository_root="${TARGET_REPO}" \
          --commitish_a="${COMMITISH_A}" \
          --commitish_b="${COMMITISH_B}" \
          --prerelease="${PRERELEASE}" \
          --prerelease_suffix="${PRERELEASE_SUFFIX}" \
          --latest_tag="${LATEST_TAG}" \
          --last_release="${LAST_RELEASE}" \
          --with_v="${WITH_V}" \
          --default_bump="${DEFAULT_BUMP}"
