name: "Determine the next semver tag to create"
description: "Determine the next semver tag to create"
inputs:
  prerelease:
    description: "If set, looks for pre-release tag patterns (v1.1.1-${suffix}.${count})"
    default: ""
  prerelease_suffix:
    description: "If prerelease is set, this string is used as the ${suffix} in the tag pattern. (Default: beta)"
    default: "beta"
  last_prerelease:
    description: "Lastest tag to bump from."
    default: ""
  last_release:
    description: "Last release tag"
    default: ""
  default_bump:
    description: "Bump version along by this. (Default: patch)"
    default: "patch"
  with_v:
    description: "New tag will start with a v prefix"
    default: "true"
  base_commitish:
    description: "Commit used to look for version bump triggers in messages"
    required: true
  head_commitish:
    description: "Commit used to look for version bump triggers in messages"
    required: true

outputs:
  prerelease:
    description: "Calculated prerelease variable."
    value: ${{ steps.get_next_tag.outputs.prerelease }}
  next_tag:
    description: "Next tag that should be created."
    value: ${{steps.get_next_tag.outputs.next_tag}}
  majors:
    description: "number of #major found."
    value: ${{steps.get_next_tag.outputs.majors}}
  minors:
    description: "number of #minor found."
    value: ${{steps.get_next_tag.outputs.minors}}
  patches:
    description: "number of #patch found."
    value: ${{steps.get_next_tag.outputs.patches}}


runs:
  using: "composite"
  steps:
##### REPEATING BLOCK >>>
    # Check running as a remote call
    - name: "Ensure running as remote"
      if: ${{ github.action_ref == '' }}
      shell: bash
      run: |
        err="ERROR: this composite action must be run via full path (eg ministryofjustice/opg-github-actions/.github/actions/terraform-version@v2.3.1)"
        echo -e "${err}"
        echo -e "${err}" >&2
        echo -e "${err}" >> $GITHUB_STEP_SUMMARY
        exit 1
    # Use bash shell script to fetch and work out releases    
    - name: "Get release binary for this runner"
      shell: bash
      id: fetch
      env:
        GH_TOKEN: ${{ github.token }}
        GH_ACTION_REPOSITORY: "${{ github.action_repository }}"
        GH_ACTION_REF: "${{ github.action_ref }}"
        GH_WORKSPACE: "${{ github.workspace }}"
        actionsRootDir: "${{ github.action_path }}/../"
      run: |
        echo -e "Get release binary"
        cd ${actionsRootDir}
        ./release-download.sh 2> $GITHUB_STEP_SUMMARY
    ## LOCAL BUILD
    # setup and build locally if the release data is not setup
    - name: "Setup go"
      uses: actions/setup-go@v4
      if: ${{ steps.fetch.outputs.RELEASE == '' }}
      with:
        go-version-file: '${{ steps.fetch.outputs.SELF_BUILD }}/./go/go.mod'
        cache: false
    - name: Build directly from source
      id: buildFromSource
      if: ${{ steps.fetch.outputs.RELEASE == '' }}
      shell: bash
      env:
        buildSource: '${{ steps.fetch.outputs.SELF_BUILD }}'
        target: '${{ steps.fetch.outputs.TARGET_BUILD }}'
      run: |
        echo -e "Build from source"
        cd ${buildSource}
        echo -e "Building (with make) for ${target}"        
        make release
        release="${buildSource}/go/builds/${target}"
        echo -e "RELEASE=${release}"
        echo "RELEASE=${release}" >> $GITHUB_OUTPUT
    ## DETERMINE BINARY PATH
    - name: "Determine binary to use"
      id: binary
      shell: bash
      env:
        direct: ${{ steps.fetch.outputs.RELEASE }}
        built: ${{ steps.buildFromSource.outputs.RELEASE }}
      run: |
        echo -e "Determine binary to use..."
        binary=""
        if [ "${direct}" != "" ]; then
          binary="${direct}"
        elif [ "${built}" != "" ]; then
          binary="${built}"
        fi
        if [ "${binary}" == "" ]; then
          err="error: no binary found"
          echo -e "${err}"
          echo -e "${err}" >&2
          echo -e "${err}" >> $GITHUB_STEP_SUMMARY
        fi
        echo -e "binary=${binary}"
        echo "binary=${binary}" >> $GITHUB_OUTPUT
    ### CHECKOUT
    # get our the calling repo as we need to access files form there
    - name: "Checkout calling repository"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: '${{ github.workspace}}/_target'
        fetch-depth: 0
        fetch-tags: true
    ##### <<< END REPEATING BLOCK 
    #### COMMANDS    
    - name: "next-tag" 
      id: "get_next_tag"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}
        APP_BIN: "${{ steps.binary.outputs.binary }}"
        repository: '${{ github.workspace}}/_target'        
        prerelease: '${{ inputs.prerelease }}'
        prereleaseSuffix: '${{ inputs.prerelease_suffix }}'
        lastRelease: '${{ inputs.last_release }}'
        lastPrerelease: '${{ inputs.last_prerelease }}'
        withV: '${{ inputs.with_v }}'
        defaultBump: '${{ inputs.default_bump }}'
        head: '${{ inputs.head_commitish }}'
        base: '${{ inputs.base_commitish }}'
        extraMsg: '${{ github.event.pull_request.title }}${{ github.event.pull_request.body }}'
      run:
        echo -e "Running next-tag"

        ${APP_BIN} next-tag --repository="${repository}" --base="${base}" --head="${head}" --last-release="${lastRelease}" --last-prerelease="${lastPrerelease}" --prerelease="${prerelease}" --prerelease-suffix="${prereleaseSuffix}" --with-v="${withV}" --default-bump="${defaultBump}" --extra-message="${extraMsg}"
    