name: "Branch Name"
description: "Get branch data. Example: ref/heads/main-123-456-789 => main-123-456-789. Also return safe-strings versions."
inputs:
   ## Used to capture the intial values before they get overwritten
  action_ref:
    description: "Capture the starting value of github.action_ref. DO NOT SET"
    default: ${{ github.action_ref }}
  action_repository:
    description: "Capture the starting value of github.action_repository. DO NOT SET"
    default: ${{ github.action_repository }}

outputs:
  branch_name:
    description: "Branch name"
    value: ${{ steps.safe.outputs.branch_name }}
  full_length:
    description: 'Alphanumeric, lowercase, but full length version of the branch.'
    value: ${{ steps.safe.outputs.full_length }}
  safe:
    description: 'Alphanumeric and lowercase version of the branch, trimmed to 12 characters.'
    value: ${{ steps.safe.outputs.safe }}
  source_commitish:
    description: "Commit hashes / branches can be used for comparisions later"
    value: ${{ steps.safe.outputs.source_commitish }}
  destination_commitish:
    description: "Commit hashes / branches can be used for comparisions later"
    value: ${{ steps.safe.outputs.destination_commitish }}

runs:
  using: "composite"
  steps:
    - name: "Checkout this actions repo into a subfolder at this version"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.action_repository }}
        ref: ${{ inputs.action_ref }}
        path: ./_ghbranchnameaction
    - name: "Setup python and pip cache"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: GitPython
      shell: bash
      run: |
        pip3 install -q git+https://github.com//gitpython-developers/GitPython@44102f30eaadcd122899f5f801f28b83bd9a5111
    - name: natsort
      shell: bash
      run: |
        pip3 install -q git+https://github.com//SethMMorton/natsort@d9503c08f8f83ce8a89bfcc45fec136868756243
    - name: semver
      shell: bash
      run: |
        pip3 install -q git+https://github.com/python-semver/python-semver.git@ec9348aefd8e9f287f451fcf2e837621a40e3ca4
    - name: Generate branch info
      id: safe
      shell: bash
      env:
        ACTION_SRC: "./_ghbranchnameaction/pyactions/actions"
        RUN_AS_TEST: ${{inputs.test}}
      run: |
        echo -e "# branch-name setup:"
        echo -e "ACTION_SRC: ${ACTION_SRC}"
        echo -e "RUN_AS_TEST: ${RUN_AS_TEST}"

        python ${ACTION_SRC}/./branch_name.py \
          --event_name="${GITHUB_EVENT_NAME}" \
          --event_data_file="${GITHUB_EVENT_PATH}"
