name: "Branch Name"
description: "Get branch data. Example: ref/heads/main-123-456-789 => main-123-456-789. Also return safe-strings versions."
inputs:
   ## Used to capture the intial values before they get overwritten
  action_ref:
    description: "Capture the starting value of github.action_ref. DO NOT SET"
    default: ${{ github.action_ref }}
  action_repository:
    description: "Capture the starting value of github.action_repository. DO NOT SET"
    default: ${{ github.action_repository }}

outputs:
  branch_name:
    description: "Branch name"
    value: ${{ steps.safe.outputs.branch_name }}
  full_length:
    description: 'Alphanumeric, lowercase, but full length version of the branch.'
    value: ${{ steps.safe.outputs.full_length }}
  safe:
    description: 'Alphanumeric and lowercase version of the branch, trimmed to 12 characters.'
    value: ${{ steps.safe.outputs.safe }}
  source_commitish:
    description: "Commit hashes / branches can be used for comparisions later"
    value: ${{ steps.safe.outputs.source_commitish }}
  destination_commitish:
    description: "Commit hashes / branches can be used for comparisions later"
    value: ${{ steps.safe.outputs.destination_commitish }}

runs:
  using: "composite"
  steps:
    - name: "Checkout this actions repo into a subfolder at this version"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.action_repository || github.repository }}
        ref: ${{ inputs.action_ref || github.ref_name }}
        path: ./_ghbranchnameaction
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: pip
      shell: bash
      env:
        PY_APP_DIR: "${{github.workspace}}/_ghbranchnameaction/python"
      run: |
        echo -e "# pip setup:"
        echo -e "PY_APP_DIR: ${PY_APP_DIR}"
        cd ${PY_APP_DIR}
        pip install -q -r ./requirements.txt
        pip install -e .
    - name: Generate branch info
      id: safe
      shell: bash
      env:
        PY_APP_DIR: "${{github.workspace}}/_ghbranchnameaction/python"
        RUN_AS_TEST: ${{inputs.test}}
      run: |
        echo -e "# branch-name setup:"
        echo -e "PY_APP_DIR: ${PY_APP_DIR}"
        echo -e "RUN_AS_TEST: ${RUN_AS_TEST}"
        cd ${PY_APP_DIR}

        python ./actions/commands/branch_name.py \
          --event_name="${GITHUB_EVENT_NAME}" \
          --event_data_file="${GITHUB_EVENT_PATH}"
