name: "Branch Name"
description: "Get branch data. Example: ref/heads/main-123-456-789 => main-123-456-789. Also return safe-strings versions."

inputs:
  action_repository:
    description: "Capture the starting value of github.action_repository. DO NOT CHANGE."
    default: ${{ github.action_repository }}
  action_ref:
    description: "Capture the starting value of github.action_ref. DO NOT CHANGE."
    default: ${{ github.action_ref }}
  action_source:
    description: "File path for action code. DO NOT CHANGE"
    default: "./_gh_action_remote_branch_name_source"

outputs:
  branch_name:
    description: "Branch name"
    value: ${{ steps.safe.outputs.branch_name }}
  full_length:
    description: 'Alphanumeric, lowercase, but full length version of the branch.'
    value: ${{ steps.safe.outputs.full_length }}
  safe:
    description: 'Alphanumeric and lowercase version of the branch, trimmed to 12 characters.'
    value: ${{ steps.safe.outputs.safe }}
  source_commitish:
    description: "Commit hashes / branches can be used for comparisions later"
    value: ${{ steps.safe.outputs.source_commitish }}
  destination_commitish:
    description: "Commit hashes / branches can be used for comparisions later"
    value: ${{ steps.safe.outputs.destination_commitish }}

runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        echo "github.action_ref=${{ github.action_ref }}"
        echo "github.action_repository=${{ github.action_repository }}"
        echo "inputs.action_repository=${{ inputs.action_repository }}"
        echo "inputs.action_ref=${{ inputs.action_ref }}"
    - name: "Checkout action content"
      uses: actions/checkout@v4
      if: ${{ inputs.action_repository != '' }}
      with:
        repository: ${{ inputs.action_repository }}
        ref: ${{ inputs.action_ref }}
        path: ${{ inputs.action_source }}
    - name: "Setup python and pip cache"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: "Install python requirements via pip [as non-action]"
      shell: bash
      if: ${{ inputs.action_repository == '' }}
      run: |
        pip install -q -r ./requirements.txt

    - name: "Install python requirements via pip [as action]"
      shell: bash
      if: ${{ inputs.action_repository != '' }}
      run: |
        pip install -q -r ${{ inputs.action_source }}/./requirements.txt

    - name: Generate branch info
      id: safe
      shell: bash
      env:
        RUN_AS_TEST: ${{inputs.test}}
      run: |
        src="${{github.action_path}}"
        python ${src}/./branch-name.py \
          --event_name="${GITHUB_EVENT_NAME}" \
          --event_data_file="${GITHUB_EVENT_PATH}"
