name: "[Test] GitHub Action setup"
description: >
  DO NOT USE. This action is only meant for discovery and testing purposed to help
  determine values of various github.action_$x context values when importing from
  external workflows in various ways (semver tag, sha, latest etc).

runs:
  using: "composite"
  steps:
    - name: "github action info"
      shell: bash
      env:
        action_repository: ${{ github.action_repository }}
        action_path: ${{ github.action_path }}
        action_ref: ${{ github.action_ref }}
      run: |
        echo "action_repository: ${{ env.action_repository }}"
        echo "action_path: ${{ env.action_path }}"
        echo "action_ref: ${{ env.action_ref }}"
    - name: "list action path"
      shell: bash
      env:
        root_path: "${{ github.action_path }}/../../"
      run: |
        cd ${{ env.root_path }}
        ls -lat
