name: "Create a new git tag at the commitish passed"
description: "Create a new git tag at the commitish passed"
inputs:  
  commitish:
    description: "The github commit reference to checkout to and create the tag at"
    required: true
  tag_name:
    description: "Name of the tag to create"
    required: true
  test:
    description: "If set, tag is not pushed to the remote."
    default: ""
  caller_repo_subfolder:
    description: "Location to checkout active repository into. (Default: ./create-tag-caller-repository)"
    default: "./create-tag-caller-repository"


outputs:
  commitish:
    description: "Inputed commitish variable."
    value: ${{ inputs.commitish }}
  tag_name:
    description: "Inputed tag_name variable."
    value: ${{ inputs.tag_name }}
  test:
    description: "Inputed test variable."
    value: ${{ inputs.test }}

  latest:
    description: "Latest tag found at commitish provided"
    value: ${{steps.tags_found.outputs.latest_tag}}
  created:
    description: "If inputted tag_name is created, then this variable should match that. If test is true, then the tag wont actually be created, but this variable will be set correctly."
    value: ${{steps.tags_found.outputs.created_tag}}
  all:
    description: "All tags (comma seperated) that are found to be pointing to inputted commish"
    value: ${{steps.tags_found.outputs.all_tags}}

runs:
  using: "composite"
  steps:
    - name: "Checkout original repo to set folder"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.head_ref }}
        path: ${{inputs.caller_repo_subfolder}}
        fetch-tags: true
        fetch-depth: 0
    - name: Create tag
      id: create_tag
      shell: bash
      working-directory: ${{inputs.caller_repo_subfolder}}
      run: |
        git tag "${{inputs.tag_name}}" "${{inputs.commitish}}"
    - name: Tags for commit
      id: tags_found
      shell: bash
      working-directory: ${{inputs.caller_repo_subfolder}}
      run: |    
        set -e    
        git tag --points-at="${{inputs.commitish}}" --sort=creatordate | sort --version-sort -f > _taglist
        all_tags_at_commit=$(cat _taglist )
        all_tags=$(cat _taglist | tr '\n', ',')
        latest_tag=$(cat _taglist | tail -n1)
        created_tag=$(cat _taglist | grep "${{inputs.tag_name}}$" | tail -n1)
        
        echo "all_tags=${all_tags}"
        echo "latest_tag=${latest_tag}"
        echo "created_tag=${created_tag}"

        echo "all_tags=${all_tags}" >> $GITHUB_OUTPUT
        echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT
        echo "created_tag=${created_tag}" >> $GITHUB_OUTPUT

    - name: Push tag
      id: push_tag
      shell: bash
      if: ${{ inputs.test == '' }}
      working-directory: ${{inputs.caller_repo_subfolder}}
      run: |
        git push origin "${{inputs.tag_name}}"
