name: "Create a new git tag at the commitish passed"
description: "Create a new git tag at the commitish passed"
inputs:  
  commitish:
    description: "The github commit reference to checkout to and create the tag at"
    required: true
  tag_name:
    description: "Name of the tag to create"
    required: true
  test:
    description: "If set, tag is not pushed to the remote."
    default: ""
  caller_repo_subfolder:
    description: "Location to checkout active repository into. (Default: ./create-tag-caller-repository)"
    default: "./create-tag-caller-repository"


outputs:
  commitish:
    description: "Inputed commitish variable."
    value: ${{ inputs.commitish }}
  original_tag_name:
    description: "Inputed tag_name variable."
    value: ${{ inputs.tag_name }}
  test:
    description: "Inputed test variable."
    value: ${{ inputs.test }}

  latest:
    description: "Latest tag found at commitish provided. This will be the 'biggest' release number and may not match the created tag."
    value: ${{steps.create_tag.outputs.latest_tag}}
  created:
    description: "The tag name that is created. It may differ from inputs.tag_name if this tag already exists. Compare to requested variable to see if these match"
    value: ${{steps.create_tag.outputs.created_tag}}
  requested:
    description: "The tag name that was requested to be created. May differ from the created tag if there is a name clash."
    value: ${{steps.create_tag.outputs.requested_tag}}

  all:
    description: "All tags (comma seperated) that are found to be pointing to inputted commish"
    value: ${{steps.create_tag.outputs.all_tags}}

runs:
  using: "composite"
  steps:
    - name: "Checkout original repo to set folder"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.head_ref }}
        path: ${{inputs.caller_repo_subfolder}}
        fetch-tags: true
        fetch-depth: 0
    - name: Install libs
      id: install_libs
      shell: bash
      run: |
        pip3 install git+https://github.com/python-semver/python-semver.git@3.0.2 -q -q
        pip3 install git+https://github.com//gitpython-developers/GitPython.git@3.1.40 -q -q
        pip3 install git+https://github.com//SethMMorton/natsort@8.4.0 -q -q
    - name: Create tag
      id: create_tag
      shell: bash
      env:
        RUN_AS_TEST: ${{inputs.test}}
      run: |      
        src="${{github.action_path}}"
        repo="${{github.workspace}}/${{inputs.caller_repo_subfolder}}"
        python ${src}/./create-tag.py \
          --repository_root="${repo}" \
          --commitish="${{inputs.commitish}}" \
          --tag_name="${{inputs.tag_name}}"
