# Find Terraform Version from the versions.tf file
name: "Parse Terraform Version From File"
description: "Determine terraform version to use from version file"
inputs:
  terraform_directory:
    description: "Directory where terraform will be run from. Looks for versions.tf file in this path."
    required: true
  terraform_versions_file:
    description: "Name of file that contains the required_version config is stored. (Default `./versions.tf`)"
    default: "./versions.tf"
  simple_file:
    description: "If set, change the parsing to presume terraform_versions_file is a plain text file that contains only a semver string."
    default: ""
  ## Used to capture the intial values before they get overwritten
  action_ref:
    description: "Capture the starting value of github.action_ref. DO NOT SET"
    default: ${{ github.action_ref }}
  action_repository:
    description: "Capture the starting value of github.action_repository. DO NOT SET"
    default: ${{ github.action_repository }}

outputs:
  terraform_directory:
    description: "Input value of terraform_directory"
    value: ${{ inputs.terraform_directory }}
  terraform_versions_file:
    description: "Input value of terraform_versions_file"
    value: ${{ inputs.terraform_versions_file }}
  simple_file:
    description: "Input value of simple_file"
    value: ${{ inputs.simple_file }}
  version:
    description: 'Discovered terraform version range. This may be an exact number (like 1.5.5) or a semver range (like >= 1.0).'
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  
  steps:
    # Create environment variables for the action repo data and workspace
    # directories and convert those into step outputs for use in other 
    # steps
    - name: "Environment variables to step variables"
      id: gha
      shell: bash
      env: 
        GHA_REPO: "${{ github.action_repository }}"
        GHA_REF: "${{ github.action_ref }}"
        GHA_PATH: "${{ github.workspace }}/opg-gha"    
      run: |
        echo "repo=${GHA_REPO}" >> $GITHUB_OUTPUT
        echo "ref=${GHA_REF}" >> $GITHUB_OUTPUT
        echo "path=${GHA_PATH}" >> $GITHUB_OUTPUT
        echo "isSelf=${{ github.repository == 'ministryofjustice/opg-github-actions' }}" >> $GITHUB_OUTPUT
    # If we aren't being called from ourselves, then checkout the repository
    # at the commit we know of into the new path
    - name: "Checkout action [ ${{ steps.gha.outputs.isSelf }} ]"
      uses: actions/checkout@v4
      if: ${{ steps.gha.outputs.isSelf != 'true' }}
      with:
        repository: ${{ steps.gha.outputs.repo }}
        ref: ${{ steps.gha.outputs.ref }}
        path: ${{ steps.gha.outputs.path }}
    
    # If the repository property matches our own name (so a call from itself)
    # then we dont checkout anything, set the path to be from the 
    # base of self and show the last commit hash and message for debug
    #
    # If its called remotely, then checkout self into a subfolder of the
    # workspace and presume can use the env variables from the 'gha' step
    - name: "Set directory path"
      id: setPath
      shell: bash      
      env:
        JSON_DEBUG: ${{ toJSON(github) }}
      run: | 
        set -e 
        if [ "${{ steps.gha.outputs.isSelf }}" == "true" ]; then 
          echo -e "Warning: running against self."
          echo -e "Using this commit:"
          git log -n1 --format="oneline"          
          appPath="${{ github.workspace }}"
        elif [ -n "${{ steps.gha.outputs.ref}}" ]; then   
          echo -e "Running from remote workflow"       
          appPath="${{ steps.gha.outputs.path }}"
        else
          echo -e "ERROR: failed to determine location of go code"
          echo -e "ERROR: failed to determine location of action code" >> $GITHUB_STEP_SUMMARY
          echo "${JSON_DEBUG}"             
          exit 1
        fi        
        echo -e "appPath=${appPath}"
        echo "appPath=${appPath}" >> $GITHUB_OUTPUT

        ls -la ${appPath}/go/
    # Setup go
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'
    - shell: bash
      run: go version
    - name: "Build app"
      shell: bash
      run: |
        gha_os=$(uname | tr '[:upper:]' '[:lower:]')
        gha_arc=$(uname -m)
        gha_host="${gha_os}_${gha_arc}"
        cd ${{ steps.setPath.outputs.appPath }}
        pwd
        ls -la
        echo "Building (via make) for ${gha_host}"
        make ${gha_host}
        cd ${{ github.workspace }}

    - name: "JSON DEBUG [${{ steps.gha.outputs.repo == '' }}]"
      shell: bash
      env:
        JSON_DEBUG: ${{ toJSON(github) }}
      if: ${{ steps.gha.outputs.repo == '' }}
      run: |
        echo -e "github action repo was empty, debugging:"
        echo "${JSON_DEBUG}"
        
    

    # # get our the calling repo as we need to access files form there
    # - uses: actions/checkout@v4
    #   with:
    #     repository: ${{ github.repository }}
    #     ref: ${{ github.ref }}
    # # fail if directory or version file does not exist
    # - id: version
    #   name: Parse terraform version data from [${{ inputs.terraform_directory }}][${{ inputs.terraform_versions_file }}]
    #   shell: bash
    #   env:
    #     TERRAFORM_DIR: ${{ inputs.terraform_directory }}
    #     TERRAFORM_VERSIONS_FILE: ${{ inputs.terraform_versions_file }}
    #     SIMPLE_FILE: ${{ inputs.simple_file }}
    #   run: |
    #     echo -e "# terraform-version setup:"
    #     echo -e "TERRAFORM_DIR: ${TERRAFORM_DIR}"
    #     echo -e "TERRAFORM_VERSIONS_FILE: ${TERRAFORM_VERSIONS_FILE}"
    #     echo -e "SIMPLE_FILE: ${SIMPLE_FILE}"

    #     echo "version=" >> $GITHUB_OUTPUT
    #     if [ ! -d ${TERRAFORM_DIR} ]; then
    #       echo "Directory not found"
    #       exit 1
    #     fi
    #     cd ${TERRAFORM_DIR}
    #     if [ ! -f ${TERRAFORM_VERSIONS_FILE} ]; then
    #       echo "File not found"
    #       exit 1
    #     fi

    #     if [ ! -z "${SIMPLE_FILE}" ]; then
    #       echo "Presuming plain text file"
    #       terraform_version=$(cat ${TERRAFORM_VERSIONS_FILE} )
    #     else
    #       echo "Presuming terraform file"
    #       terraform_version=$(cat ${TERRAFORM_VERSIONS_FILE} | sed -r -n 's/.*required_version.*"(.*)"$/\1/p' )
    #     fi
    #     echo "version=${terraform_version}" >> $GITHUB_OUTPUT
