name: "Safe string generation"
description: "Convert a string into shortern and remove unsafe characters. If conditional_match is set and original equals this value then conditional_value is used for the outputs."
inputs:
  original:
    description: "Original string (such as branch name) to make safe for tag usage etc"
    required: true
  suffix:
    description: "Additional string at the end"
    default: ""
  conditional_match:
    description: "If the original string matches this value, then use the conditional_value directly."
    default: ""
  conditional_value:
    description: "When original matches conditional_match use this value for all other outputs directly."
    default: ""
  length:
    description: "If set, trim the string to this length"

outputs:
  original:
    description: "Original string"
    value: ${{ inputs.original }}
  suffix:
    description: "Original suffix"
    value: ${{ inputs.suffix }}
  length:
    description: "Originally requested length"
    value: ${{ steps.make_safe.outputs.length }}
  full_length:
    description: "Alphanumeric, lowercase, but full length version of the original string."
    value: ${{ steps.make_safe.outputs.full_length }}
  safe:
    description: "Alphanumeric, lowercase, trimmed to length version of the original string."
    value: ${{ steps.make_safe.outputs.safe }}

runs:
  using: "composite"
  steps:
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: GitPython
      shell: bash
      run: |
        pip3 install -q git+https://github.com//gitpython-developers/GitPython@44102f30eaadcd122899f5f801f28b83bd9a5111
    - name: natsort
      shell: bash
      run: |
        pip3 install -q git+https://github.com//SethMMorton/natsort@d9503c08f8f83ce8a89bfcc45fec136868756243
    - name: semver
      shell: bash
      run: |
        pip3 install -q git+https://github.com/python-semver/python-semver.git@ec9348aefd8e9f287f451fcf2e837621a40e3ca4
    - name: Create Safe tags
      id: make_safe
      shell: bash
      env:
        RUN_AS_TEST: ${{inputs.test}}
      run: |
        src="${{github.action_path}}"
        python ${src}/./safe-strings.py \
          --string="${{inputs.original}}" \
          --suffix="${{inputs.suffix}}" \
          --length="${{inputs.length}}" \
          --conditional_match="${{inputs.conditional_match}}" \
          --conditional_value="${{inputs.conditional_value}}"
