name: "Get the latest semver compatible tag on this repo"
description: "Use the branch name passed (can be either refs/heads/name-of-thing or just name-of-thing)."
inputs:
  test:
    description: "If set, run test versions of data"
    default: ""
  test_file:
    description: "If test is set, then use the content of this file"
    default: "./tests/tags.txt"
  prerelease:
    description: "If set, looks for pre-release tag patterns (v1.1.1-${suffix}.${count})"
    default: ""
  prerelease_suffix:
    description: "If prerelease is set, this string is used as the ${suffix} in the tag pattern. (Default: beta)"
    default: "beta"
  branch_name:
    description: "Current branch name"
    default: "beta"
  release_branches:
    description: "Branches that would trigger this as a release."
    default: "main,master"
  caller_repo_subfolder:
    description: "Location to checkout active repository into. (Default: ./latest-tag-caller-repository)"
    default: "./latest-tag-caller-repository"

  
outputs:
  test:
    description: "Inputed test."    
    value: ${{inputs.test}}
  prerelease:
    description: "Inputed prerelease variable."
    value: ${{ steps.latest.outputs.prerelease }}
  prerelease_suffix:
    description: "Inputed prerelease_suffix variable."
    value: ${{ steps.latest.outputs.prerelease_suffix }}
  latest:
    description: "Latest tag found"
    value: ${{steps.latest.outputs.latest}}
  last_release:
    description: "Last release tag found"
    value: ${{steps.latest.outputs.last_release}}


runs:
  using: "composite"
  steps:
    - name: "Checkout original repo to set folder"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: ${{inputs.caller_repo_subfolder}}
        fetch-tags: true
        fetch-depth: 0
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Get latest Tag
      id: latest
      shell: bash
      env:
        RUN_AS_TEST: ${{inputs.test}}
      run: |      
        pip install -r ./requirements.txt
        src="${{github.action_path}}"
        repo="${{github.workspace}}/${{inputs.caller_repo_subfolder}}"
        python ${src}/./latest-tag.py \
          --repository_root="${repo}" \
          --branch_name="${{inputs.branch_name}}" \
          --release_branches="${{inputs.release_branches}}" \
          --prerelease="${{inputs.prerelease}}" \
          --prerelease_suffix="${{inputs.prerelease_suffix}}" \
          --test_file="${src}/${{inputs.test_file}}"
