name: "Create semver tag at current github ref using passed branch name as a suffix."
description: "Use the branch name passed (can be either refs/heads/name-of-thing or just name-of-thing)."
inputs:
  test:
    description: "If set, run test versions of data"
    default: ""
  test_file:
    description: "If test is set, then use the content of this file"
    default: "./tests/tags.txt"
  prerelease:
    description: "If set, looks for pre-release tag patterns (v1.1.1-${suffix}.${count})"
    default: ""
  prerelease_suffix:
    description: "If prerelease is set, this string is used as the ${suffix} in the tag pattern. (Default: beta)"
    default: "beta"
  
  
outputs:
  test:
    description: "Inputed test."    
    value: ${{inputs.test}}
  prerelease:
    description: "Inputed prerelease variable."
    value: ${{ inputs.prerelease }}
  prerelease_suffix:
    description: "Inputed prerelease_suffix variable."
    value: ${{ inputs.prerelease_suffix }}
  latest:
    description: "Latest tag found"
    value: ${{steps.latest.outputs.latest}}
  # new_tag:
  #   description: "The value of the newly created tag."
  #   value: ${{ steps.create_tags.outputs.new_tag }}
  # tag:
  #   description: "The value of the latest tag after running this action."
  #   value: ${{ steps.create_tags.outputs.tag }}
  # part:
  #   description: "The part of version which was bumped."
  #   value: ${{ steps.create_tags.outputs.part }}


runs:
  using: "composite"
  steps:
    - name: debug
      shell: bash
      run: |
        pwd
        ls -la
        ls -la .github/
        ls -la .github/actions      
    - name: "Checkout original repo to set folder"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: 'target-repo'
    - name: debug
      shell: bash
      run: |
        pwd
        ls -la target-repo/
    - name: Fetch tags
      id: fetch_tags
      shell: bash
      working-directory: 'target-repo'
      run: |
        git fetch --tags
    - name: Install libs
      id: install_libs
      shell: bash
      run: |
        pip3 install git+https://github.com/python-semver/python-semver.git@3.0.2
        pip3 install git+https://github.com//gitpython-developers/GitPython.git@3.1.40
    - name: Get latest Tag
      id: latest
      shell: bash
      env:
        RUN_AS_TEST: ${{inputs.test}}
      run: |      
        src="${{github.action_path}}"
        repo="${{github.workspace}}/target-repo"
        python ${src}/./latest-tag.py \
          --repository_root="${repo}" \
          --test_file=${{inputs.test_file}} \
          --prerelease=${{inputs.prerelease}}
          --prerelease_suffix=${{inputs.prerelease_suffix}} \

    # - name: Get last tag
    #   id: last_tag
    #   shell: bash
    #   run: |
    #     src="${{github.action_path}}"
    #     python ${dir}/.github/actions/semver-tag/latest-tag.py --prerelease=${{inputs.prerelease}}
    # - name: "Create Tag"
    #   id: create_tag
    #   uses: anothrNick/github-tag-action@1.67.0
    #   env:
    #     GITHUB_TOKEN: ${{inputs.github_token}}
    #     INITIAL_VERSION: 0.0.1
    #     DEFAULT_BUMP: minor
    #     PRERELEASE_SUFFIX: ${{ steps.safe_branch.outputs.safe }}
    #     PRERELEASE: ${{ inputs.prerelease != '' }}
    #     RELEASE_BRANCHES: ${{ inputs.release_branch }}
    #     WITH_V: "true"
    #     DRY_RUN: ${{ inputs.dry_run != '' }}
