name: "Get the latest semver compatible tag on this repo"
description: "Use the branch name passed (can be either refs/heads/name-of-thing or just name-of-thing)."
inputs:
  prerelease:
    description: "If set, looks for pre-release tag patterns (v1.1.1-${suffix}.${count})"
    default: ""
  prerelease_suffix:
    description: "If prerelease is set, this string is used as the ${suffix} in the tag pattern. (Default: beta)"
    default: "beta"
  branch_name:
    description: "Current branch name"
    default: "beta"
  release_branches:
    description: "Branches that would trigger this as a release."
    default: "main,master"
  caller_repo_subfolder:
    description: "Location to checkout active repository into. (Default: ./latest-tag-caller-repository)"
    default: "./latest-tag-caller-repository"


outputs:
  prerelease:
    description: "Inputed prerelease variable."
    value: ${{ steps.latest.outputs.prerelease_calculated }}
  prerelease_suffix:
    description: "Inputed prerelease_suffix variable."
    value: ${{ steps.latest.outputs.prerelease_suffix }}
  latest:
    description: "Latest tag found"
    value: ${{steps.latest.outputs.latest}}
  last_release:
    description: "Last release tag found"
    value: ${{steps.latest.outputs.last_release}}


runs:
  using: "composite"
  steps:
    - name: "Checkout original repo to set folder"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: ${{inputs.caller_repo_subfolder}}
        fetch-tags: true
        fetch-depth: 0
    - name: "Setup python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: GitPython
      shell: bash
      run: |
        pip3 install -q git+https://github.com//gitpython-developers/GitPython@44102f30eaadcd122899f5f801f28b83bd9a5111
    - name: natsort
      shell: bash
      run: |
        pip3 install -q git+https://github.com//SethMMorton/natsort@d9503c08f8f83ce8a89bfcc45fec136868756243
    - name: semver
      shell: bash
      run: |
        pip3 install -q git+https://github.com/python-semver/python-semver.git@ec9348aefd8e9f287f451fcf2e837621a40e3ca4
    - name: Get latest Tag
      id: latest
      shell: bash
      env:
        ACTION_SRC: ${{ github.action_path }}
        TARGET_REPO: "${{github.workspace}}/${{inputs.caller_repo_subfolder}}"
        BRANCH_NAME: ${{inputs.branch_name}}
        RELEASE_BRANCHES: ${{inputs.release_branches}}
        PRERELEASE: ${{inputs.prerelease}}
        PRERELEASE_SUFFIX: ${{inputs.prerelease_suffix}}
      run: |
        echo -e "# latest-tag setup:"
        echo -e "ACTION_SRC: ${ACTION_SRC}"
        echo -e "TARGET_REPO: ${TARGET_REPO}"
        echo -e "BRANCH_NAME: ${BRANCH_NAME}"
        echo -e "RELEASE_BRANCHES: ${RELEASE_BRANCHES}"
        echo -e "PRERELEASE_SUFFIX: ${PRERELEASE_SUFFIX}"

        python ${ACTION_SRC}/./latest-tag.py \
          --repository_root="${TARGET_REPO}" \
          --branch_name="${BRANCH_NAME}" \
          --release_branches="${RELEASE_BRANCHES}" \
          --prerelease="${PRERELEASE}" \
          --prerelease_suffix="${PRERELEASE_SUFFIX}"
