name: "Create semver tag at current github sha using passed branch name as a suffix."
description: "Use the branch name passed (can be either refs/heads/name-of-thing or just name-of-thing)."
inputs:
  test:
    description: "If set, acts as a dry run without creating items"
    default: ""
  release_branch:    
    description: "Release branch main - if branch name matches this the tag change to be a production style v1.1.0 without suffixes. (Default: main)"
    default: "main"
  prerelease:
    description: "If set, creates a pre-release (draft)."
    default: ""
  with_v:
    description: "New tag will start with a v prefix is this is any non-empty value."
    default: "true"

  
outputs:
  test:
    description: "Inputed test variable."
    value: ${{ inputs.test }}
  release_branch:
    description: "Inputed release_branch variable."
    value: ${{ inputs.release_branch }}
  prerelease:
    description: "Inputed prerelease variable."
    value: ${{ inputs.prerelease }}
  
  branch_original:
    description: "Output from branch_name safety check - the branch_name return value"
    value: ${{ steps.branch_name.outputs.branch_name }}  
  branch_full_length:
    description: "Output from branch_name safety check - the full_length return value"
    value: ${{ steps.branch_name.outputs.full_length }}  
  branch_safe:
    description: "Output from branch_name safety check  - the safe return value"
    value: ${{ steps.branch_name.outputs.safe }}  
  
  latest_tag_latest:
    description: "Output from latest_tag - the latest return value"
    value: ${{ steps.latest_tag.outputs.latest }}  
  latest_tag_last_release:
    description: "Output from latest_tag - the last_release value"
    value: ${{ steps.latest_tag.outputs.last_release }}  

  next_tag:
    description: "Output from next_tag - the next_tag value"
    value: ${{ steps.next_tag.outputs.next_tag }}  

  create_tag_latest:
    description: "Output from create_tag - the latest value"
    value: ${{ steps.create_tag.outputs.latest }}  
  create_tag_created:
    description: "Output from create_tag - the created value"
    value: ${{ steps.create_tag.outputs.created }}  
  create_tag_all:
    description: "Output from create_tag - the all value"
    value: ${{ steps.create_tag.outputs.all }}  



runs:
  using: "composite"
  steps:    
    - name: "Generate safe branch name"
      id: branch_name
      uses: './.github/actions/branch-name'
      with:
        ref: "${{github.ref}}"
        head_ref: "${{github.head_ref}}"
    - name: "Find latest tag"
      id: latest_tag
      uses: './.github/actions/latest-tag'
      with:          
          branch_name: ${{steps.branch_name.outputs.branch_name}}
          release_branches: ${{inputs.release_branch}}
          prerelease: ${{inputs.prerelease}}
          prerelease_suffix: ${{steps.branch_name.outputs.safe}}
    - name: "Find next tag"
      id: next_tag
      uses: './.github/actions/next-tag'
      with:          
          prerelease: ${{steps.latest_tag.outputs.prerelease}}
          prerelease_suffix: ${{steps.latest_tag.outputs.prerelease_suffix}}
          latest_tag: ${{steps.latest_tag.outputs.latest}}
          last_release: ${{steps.latest_tag.outputs.last_release}}
          with_v: ${{inputs.with_v}}
    - name: "Create tag"
      id: create_tag
      uses: './.github/actions/create-tag'
      with:
          test: ${{inputs.test}}
          commitish: ${{steps.branch_name.outputs.branch_name}}
          tag_name: ${{steps.next_tag.outputs.next_tag}}
    - name: summary
      shell: bash
      if: always()
      run: |
        set -eo pipefail
        echo "### Semver tag summary" >> $GITHUB_STEP_SUMMARY
        echo "| Stage | Variable | Value |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
        echo "| Branch | original | ${{ steps.branch_name.outputs.original }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Branch | safe | ${{ steps.branch_name.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Branch | full_length | ${{ steps.branch_name.outputs.full_length }} |"  >> $GITHUB_STEP_SUMMARY          
        echo "| Latest Tag | latest | ${{ steps.latest_tag.outputs.latest }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Latest Tag | last_release | ${{ steps.branch_name.latest_tag.last_release }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Next Tag | latest | ${{ steps.next_tag.outputs.latest }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Next Tag | last_release | ${{ steps.branch_name.next_tag.last_release }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Next Tag | next_tag | ${{ steps.branch_name.next_tag.next_tag }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Create Tag | latest | ${{ steps.branch_name.create_tag.latest }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Create Tag | all | ${{ steps.branch_name.create_tag.all }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| Create Tag | created | ${{ steps.branch_name.create_tag.created }} |"  >> $GITHUB_STEP_SUMMARY
        


