name: "Create semver tag at current github sha using passed branch name as a suffix."
description: "Use the branch name passed (can be either refs/heads/name-of-thing or just name-of-thing)."
inputs:
  test:
    description: "If set, acts as a dry run without creating items"
    default: ""
  release_branch:    
    description: "Release branch main - if branch name matches this the tag change to be a production style v1.1.0 without suffixes. (Default: main)"
    default: "main"
  prerelease:
    description: "If set, creates a pre-release (draft)."
    default: ""
  
outputs:
  test:
    description: "Inputed test variable."
    value: ${{ inputs.test }}
  release_branch:
    description: "Inputed release_branch variable."
    value: ${{ inputs.release_branch }}
  prerelease:
    description: "Inputed prerelease variable."
    value: ${{ inputs.prerelease }}
  
  branch_original:
    description: "Output from branch_name safety check - the branch_name return value"
    value: ${{ steps.branch_name.outputs.branch_name }}  
  branch_full_length:
    description: "Output from branch_name safety check - the full_length return value"
    value: ${{ steps.branch_name.outputs.full_length }}  
  branch_safe:
    description: "Output from branch_name safety check  - the safe return value"
    value: ${{ steps.branch_name.outputs.safe }}  
  
  latest_tag_latest:
    description: "Output from latest_tag - the latest return value"
    value: ${{ steps.latest_tag.outputs.latest }}  
  latest_tag_last_release:
    description: "Output from latest_tag - the last_release value"
    value: ${{ steps.latest_tag.outputs.last_release }}  

  next_tag:
    description: "Output from next_tag - the next_tag value"
    value: ${{ steps.next_tag.outputs.next_tag }}  

  create_tag_latest:
    description: "Output from create_tag - the latest value"
    value: ${{ steps.create_tag.outputs.latest }}  
  create_tag_created:
    description: "Output from create_tag - the created value"
    value: ${{ steps.create_tag.outputs.created }}  
  create_tag_all:
    description: "Output from create_tag - the all value"
    value: ${{ steps.create_tag.outputs.all }}  



runs:
  using: "composite"
  steps:
    - name: "Generate safe branch name"
      id: branch_name
      uses: './.github/actions/branch-name'
      with:
        ref: "${{github.ref}}"
        head_ref: "${{github.head_ref}}"
    - name: "Find latest tag"
      id: latest_tag
      uses: './.github/actions/latest-tag'
      with:          
          branch_name: ${{steps.branch_name.outputs.branch_name}}
          release_branches: ${{inputs.release_branch}}
          prerelease: ${{inputs.prerelease}}
          prerelease_suffix: ${{steps.branch_name.outputs.safe}}
    - name: "Find next tag"
      id: next_tag
      uses: './.github/actions/next-tag'
      with:          
          sha: ${{github.event.repository.sha}}
          prerelease: ${{steps.latest_tag.outputs.prerelease}}
          prerelease_suffix: ${{steps.latest_tag.outputs.prerelease_suffix}}
          latest_tag: ${{steps.latest_tag.outputs.latest}}
          last_release: ${{steps.latest_tag.outputs.last_release}}
          with_v: true
    - name: "Create tag"
      id: create_tag
      uses: './.github/actions/create-tag'
      with:
          test: ${{inputs.test}}
          commitish: ${{github.event.repository.sha}}
          tag_name: ${{steps.next_tag.outputs.next_tag}}
