name: "Event Data"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  info:
    if: always()
    name: info
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo -e "PUSH"
          echo -e "before=${{github.event.before}}"
          echo -e "after=${{github.event.after}}"
          echo -e "ref=${{github.event.ref}}"

          echo -e "before=${{github.before}}"
          echo -e "after=${{github.after}}"
          echo -e "ref=${{github.ref}}"
          more $GITHUB_EVENT_PATH
