name: "Event Data"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  info:
    if: always()
    name: info
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo -e "PUSH"
          echo -e "before=${{github.event.before}}"
          echo -e "after=${{github.event.after}}"
          echo -e "ref=${{github.event.ref}}"
          echo -e "ref=${{github.ref}}"

          echo -e "PULL_REQUEST"
          echo -e "github.event.pull_request.base.ref=${{github.event.pull_request.base.ref}}"
          echo -e "github.event.pull_request.head.ref=${{github.event.pull_request.head.ref}}"
          echo -e "${GITHUB_EVENT_PULLREQUEST_BASE_REF}"
          echo -e "${GITHUB_EVENT_PULL_REQUEST_BASE_REF}"


          echo -e "default_branch=${{github.event.repository.default_branch}}"
          more $GITHUB_EVENT_PATH
