name: "Event Data"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  info:
    if: always()
    name: info
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          echo -e "github.event.pull_request.base.ref=${{github.event.pull_request.base.ref}}"
          echo -e "github.event.pull_request.head.ref=${{github.event.pull_request.base.ref}}"
          echo -e "github.event.pull_request.repository.default_branch=${{github.event.pull_request.repository.default_branch}}"

          echo -e "github.event.push.ref=${{github.event.push.ref}}"
          echo -e "github.event.push.repository.default_branch=${{github.event.push.repository.default_branch}}"
          more $GITHUB_EVENT_PATH
