name: "[Pull Request] Workflow (Updated)"

on:
  pull_request:
    branches: [main]
    paths-ignore: ['terraform/**', '.github/workflows/_terraform.yml']

jobs:
  # test actions
  run_tests:
    name: "[Tests]"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit



  pr_workflow:
    needs: [run_tests]
    name: "PR Workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout self"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Build"
        id: build
        shell: bash
        env:
          appPath: '${{ github.workspace }}/go'
        run: |
          echo -e "Building"
          gha_os=$(uname | tr '[:upper:]' '[:lower:]')
          gha_arc=$(uname -m)
          target="${gha_os}_${gha_arc}"
          
          cd ${appPath}
          pwd 
          ls -la
          
          echo -e "Building (via make) for ${target}"
          make ${target}
          cd ${{ github.workspace }}
      - name: "Semver tag and release"
        id: semver_tag
        uses: ./.github/actions/semver-tag
        with:
          test: false
          prerelease: true
          releases_enabled: false # disable the release as we make here and include build assests
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create a release [${{ steps.semver_tag.outputs.created_tag }}]"
        id: create_release      
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ steps.semver_tag.outputs.created_tag }}
          name: ${{ steps.semver_tag.outputs.created_tag }}
          draft: true
          prerelease: true
          generateReleaseNotes: true
          artifacts: '${{ github.workspace }}/go/builds/*.tar'
            

  end:
    name: 'End of PR workflow'
    runs-on: 'ubuntu-latest'
    needs: [run_tests, pr_workflow]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
