name: "[Pull Request] Workflow (Updated)"

on:
  pull_request:
    branches: [main]
    paths-ignore: ['terraform/**', '.github/workflows/_terraform.yml']

jobs:
  # test actions
  run_tests:
    name: "[Tests]"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit



  pr_workflow:
    name: "PR Workflow"
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - name: "Checkout self"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Semver tag and release"
        id: semver_tag
        uses: ./.github/actions/semver-tag
        with:
          test: true
          prerelease: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          

  end:
    name: 'End of PR workflow'
    runs-on: 'ubuntu-latest'
    needs: [run_tests]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
