name: "[Pull Request] Workflow"

on:
  pull_request:
    branches: [main]
    paths-ignore: ['terraform/**', '.github/workflows/_terraform.yml']

jobs:
  # test actions
  run_tests:
    name: "[Tests]"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit

  # generate branch name
  branch_name:
    needs:
      - run_tests
    name: "Branch name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@v2.0.0
    secrets: inherit

  # generate semver tag
  semver_tag:
    needs: [branch_name]
    name: "Tag [${{ needs.branch_name.outputs.original }}]"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-semver-tag.yml@v2.0.0
    with:
      branch_name: ${{ needs.branch_name.outputs.original }}
    secrets: inherit

  # Output summary data
  summary:
    if: always()
    name: PR
    runs-on: 'ubuntu-latest'
    needs: [branch_name, semver_tag, create_release]
    steps:
      - id: summary
        name: "Summary"
        run: |
          echo "### PR Information" >> $GITHUB_STEP_SUMMARY
          echo "| Segment | Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| Branch | Original | ${{ needs.branch_name.outputs.original }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Branch | Safe | ${{ needs.branch_name.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Branch | Full Length | ${{ needs.branch_name.outputs.full_length }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Semver | Tag | ${{ needs.semver_tag.outputs.tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Semver | New Tag | ${{ needs.semver_tag.outputs.new_tag }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Semver | Pre-release | ${{ needs.semver_tag.outputs.prerelease }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| Release | Draft | true |" >> $GITHUB_STEP_SUMMARY
          echo "| Release | Pre-release | true |" >> $GITHUB_STEP_SUMMARY
          echo "| Release | Notes | true |" >> $GITHUB_STEP_SUMMARY
          echo "| Release | URL | [${{ needs.create_release.outputs.id }}](${{ needs.create_release.outputs.html_url }}) |"  >> $GITHUB_STEP_SUMMARY

  end:
    name: 'End of PR workflow'
    runs-on: 'ubuntu-latest'
    needs: [branch_name, semver_tag, create_release, summary]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
