name: "[Pull Request] Workflow"

on:
  pull_request:
    branches: [main]
    paths-ignore: ['terraform/**', '.github/workflows/_terraform.yml']

jobs:
  # test actions
  run_tests:
    name: "[Tests]"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit

  pr_workflow:
    name: "PR Workflow"
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - name: "Checkout self"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Semver tag and release"
        id: semver_tag
        uses: ./.github/actions/semver-tag
        with:
          prerelease: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: summary
        name: "Summary"
        if: always()
        run: |
          echo "### PR Information" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| branch | ${{ steps.semver_tag.outputs.branch_original }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| branch_safe | ${{ steps.semver_tag.outputs.branch_safe }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| prerelease | ${{ steps.semver_tag.outputs.prerelease }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| lastest_tag | ${{ steps.semver_tag.outputs.latest_tag_latest }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| last_release | ${{ steps.semver_tag.outputs.latest_tag_last_release }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| realease | [${{ steps.semver_tag.outputs.release_id }}](${{ steps.semver_tag.outputs.release_url }})  |"  >> $GITHUB_STEP_SUMMARY
          echo "| **created_tag** | **${{ steps.semver_tag.outputs.created_tag }}** |"  >> $GITHUB_STEP_SUMMARY

  end:
    name: 'End of PR workflow'
    runs-on: 'ubuntu-latest'
    needs: [pr_workflow]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
