name: "[Release] Versioning workflows"

on:
  push:
    branches: [main]
    paths-ignore: ['terraform/**', '.github/workflows/_terraform.yml']

jobs:
  # test actions
  run_tests:
    name: "[Tests]"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit

  release_workflow:
    name: "Release Workflow"
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - name: "Checkout self"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Semver tag and release"
        id: semver_tag
        uses: ./.github/actions/semver-tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          show_verbose_summary: true



  end:
    name: 'End of release workflow'
    runs-on: 'ubuntu-latest'
    needs: [release_workflow]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
