name: "[Data] Test python code"

on:
  workflow_dispatch:
  workflow_call:

jobs:

  # test terraform-workspace-manager
  test_terraform_workspace_manager:
    name: "terraform-workspace-manager"
    uses: './.github/workflows/test-terraform-workspace-manager.yml'
    secrets: inherit

  test_go:
    name: "go test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go/go.mod'        
          cache-dependency-path: './go/go.sum'
      - name: "Go paths"
        id: gobin
        run: |
          go version          
          gb=$(go env GOPATH)/bin          
          echo "gobin=${gb}"
      - name: "Running tests"       
        env:
          GOBIN: ${{steps.gobin.outputs.gobin}}
        run: |          
          cd ./go
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -v -json -count=5 ./... 2>&1 | go-junit-report -parser gojson -out report.xml -set-exit-code
          ls -la
      - name: Test Report
        id: report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results          
          path: ./go/report.xml 
          reporter: jest-junit
      - name: Output results link
        run:  |
          echo "**[Test results](${{steps.report.outputs.url_html}})**" >> $GITHUB_STEP_SUMMARY
