name: "[Data] Test python code"

on:
  workflow_dispatch:
  workflow_call:

jobs:

  # test terraform-workspace-manager
  test_terraform_workspace_manager:
    name: "terraform-workspace-manager"
    uses: './.github/workflows/test-terraform-workspace-manager.yml'
    secrets: inherit

  test_go:
    name: "go test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go/go.mod'        
          cache-dependency-path: |
            ./go/go.sum 
      - run: go version
      - run: |
          echo -e "Running tests"
          cd ./go
          go test -v ./...