name: "[Data] Test python code"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  # test terraform-version
  test_terraform_version:
    name: "terraform-version"
    uses: './.github/workflows/test-terraform-version.yml'

  # test terraform-workspace-manager
  test_terraform_workspace_manager:
    name: "terraform-workspace-manager"
    uses: './.github/workflows/test-terraform-workspace-manager.yml'
    secrets: inherit

  # test terraform-workspace-manager
  test_semver_tag:
    name: "semver-tag"
    uses: './.github/workflows/test-semver-tag.yml'

  # test the python library
  test_python_app_code:
    name: "pytest suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Setup pip"
        run: |
          cd ./python
          pip install -q -r ./requirements.txt
          pip install -e .
      - name: "Setup and run pytest"
        shell: bash
        env:
          RUN_AS_TEST: "true"
        run: |
          cd ./python
          git config --global user.name "pytest"
          git config --global user.email "dummy@dummymail.com"
          pytest ./tests/
          echo "$(cat ./branch_name_results.md)" >> $GITHUB_STEP_SUMMARY
          echo "$(cat ./create_tag_results.md)" >> $GITHUB_STEP_SUMMARY
          echo "$(cat ./latest_tag_results.md)" >> $GITHUB_STEP_SUMMARY
          echo "$(cat ./next_tag_results.md)" >> $GITHUB_STEP_SUMMARY
          echo "$(cat ./safe_strings_results.md)" >> $GITHUB_STEP_SUMMARY
