name: "[Data] Test application code"

on:
  workflow_dispatch:
  workflow_call:

jobs:

  # test terraform-workspace-manager
  test_terraform_workspace_manager:
    name: "terraform-workspace-manager"
    uses: './.github/workflows/test-terraform-workspace-manager.yml'
    secrets: inherit

  test_go:
    name: "Go test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go/go.mod'        
          cache: false
      - name: "Running tests"
        env:
          LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}
          LOG_TO: "stdout"
          GITHUB_TOKEN: ${{ github.token }}
        run: |          
          cd ./go
          go install github.com/jstemmer/go-junit-report/v2@latest
          echo "" > report.xml
          go test -v -json -bench -count=5 ./... > test-results.json 2>&1 || true
          go-junit-report -parser gojson -in test-results.json -out report.xml || true

      - name: Test Report
        id: report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results          
          fail-on-error: false
          path: ./go/report.xml 
          reporter: java-junit
      - name: Output results link
        run:  |
          echo "**[Test results](${{steps.report.outputs.url_html}})**" >> $GITHUB_STEP_SUMMARY
      - name: Test failure
        if: ${{ steps.report.outputs.conclusion != 'success' }}
        run: |
          echo "Test failed, please see summary: ${{steps.report.outputs.url_html}}"
          exit 1
      
