name: "[Data] Test actions"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  # test terraform-version
  test_terraform_version:
    name: "terraform-version"
    uses: './.github/workflows/test-terraform-version.yml'

  # test terraform-workspace-manager
  test_terraform_workspace_manager:
    name: "terraform-workspace-manager"
    uses: './.github/workflows/test-terraform-workspace-manager.yml'
    secrets: inherit

  # test safe-strings
  test_safe_strings:
    name: "safe-strings"
    uses: './.github/workflows/test-safe-strings.yml'

  # test safe-strings
  test_branch_name:
    name: "branch-name"
    uses: './.github/workflows/test-branch-name.yml'

  # test latest-tag
  test_latest_tag:
    name: "latest-tag"
    uses: './.github/workflows/test-latest-tag.yml'

  # test next-tag
  test_next_tag:
    name: "next-tag"
    uses: './.github/workflows/test-next-tag.yml'

  # test create-tag
  test_create_tag:
    name: "create-tag"
    uses: './.github/workflows/test-create-tag.yml'

  # test semver-tag
  test_semver:
    name: "semver-tag"
    uses: './.github/workflows/test-semver-tag.yml'
