name: "[Data] Test application code"

on:
  workflow_dispatch:
  workflow_call:

jobs:

  # test terraform-workspace-manager
  test_terraform_workspace_manager:
    name: "terraform-workspace-manager"
    uses: './.github/workflows/test-terraform-workspace-manager.yml'
    secrets: inherit
  
  # test the generation of release notes in the bash script
  test_release_notes_script:
    name: "release-notes-bash-script"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: "Run make test_release_notes"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          make test_release_notes
  
  # test the release download script works for self
  # and a known version
  test_release_download_script:
    name: "release-download-bash-script"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: "Run make test_release_download_self_build"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: |
          make test_release_download_self_build
      - name: "Run make test_release_download_binary"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: |
          make test_release_download_binary
    
  # test semver runs with empty prerelease
  test_semver_action:
    name: "Semver when theres no prerelease flag (issue 48)"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: "semvertest"
        name: "Test semver tag and release"
        uses: ./.github/actions/semver-tag
        with:          
          test: true
          releases_enabled: false
      - name: "Check prerelease output is [${{ env.prereleaseShouldBe }}]"
        env:
          prereleaseShouldBe: ${{ github.ref == 'refs/heads/main' && 'false' || 'true' }}
          preRel: ${{ steps.semvertest.outputs.latest_tag_prerelease }}
          ogPreRel: ${{ steps.semvertest.outputs.latest_tag_original_prerelease }}
        run: |
            echo -e "Check prerelease information aligns"
            if [ "${{ env.preRel }}" != "${{ env.prereleaseShouldBe }}" ]; then
              echo -e "Prelease failure" 
              exit 1
            fi
            if [ "${{ env.ogPreRel }}" != "${{ env.prereleaseShouldBe }}" ]; then
              echo -e "Original release failure"
              exit 1
            fi
          
  # run the full go test suite for this app
  test_go:
    name: "Go test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go/go.mod'        
          cache: false
      - name: "Running tests"
        env:
          LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}
          LOG_TO: "stdout"
          GITHUB_TOKEN: ${{ github.token }}
        run: |          
          cd ./go
          go install github.com/jstemmer/go-junit-report/v2@latest
          echo "" > report.xml
          go test -v -json -bench -count=5 ./... > test-results.json 2>&1 || true
          go-junit-report -parser gojson -in test-results.json -out report.xml || true
        # generate test report for this run
      - name: Test Report
        id: report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results          
          fail-on-error: false
          path: ./go/report.xml 
          reporter: java-junit
      - name: Output results link
        run:  |
          echo "**[Test results](${{steps.report.outputs.url_html}})**" >> $GITHUB_STEP_SUMMARY
      - name: Test failure
        if: ${{ steps.report.outputs.conclusion != 'success' }}
        run: |
          echo "Test failed, please see summary: ${{steps.report.outputs.url_html}}"
          exit 1
      
