name: "[Data] Test python code"

on:
  workflow_dispatch:
  workflow_call:

jobs:

  # test terraform-workspace-manager
  test_terraform_workspace_manager:
    name: "terraform-workspace-manager"
    uses: './.github/workflows/test-terraform-workspace-manager.yml'
    secrets: inherit

  test_go:
    name: "go test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go/go.mod'        
          cache-dependency-path: './go/go.sum'
      - name: "Go paths"
        id: gobin
        run: |
          go version          
          gb=$(go env GOPATH)/bin          
          echo "gobin=${gb}"
      - name: "Running tests"       
        env:
          GOBIN: ${{steps.gobin.outputs.gobin}}
        run: |          
          cd ./go
          go install github.com/jstemmer/go-junit-report/v2@latest
          echo "here1"
          go test -v -json -bench -count=5 ./...
          echo "here2"
          ls -la
          # go-junit-report \
          #   -in="./testresult.json"
          #   -parser=gojson \
          #   -set-exit-code \
          #   -package-name="opg-github-actions" > report.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results          
          path: ./go/report.xml 
          reporter: jest-junit