name: "[Test] branch-name"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test create-tag"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test a known ref that should return a preexisting semver tag"
        uses: './.github/actions/create-tag'
        with:
          dry_run: true
          ref: "dab1b63"
          tag_name: "test_tag_wont_be_found"
      - id: test_results
        name: Test results
        run: |
          t1="v1.4.0"
          
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| 1. | ${t1} | ${{steps.test1.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          
