name: "[Test] next-tag"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test next-tag"
    steps:
      - 
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: t1_1
        name: "1.1 Test major version bump as a new prerelease (with v)"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          latest_tag: "v1.5.0-moreactions.1"
          last_release: "v1.4.0"
          with_v: true
      - id: t1_2
        name: "1.2 Test major version bump as an existing prerelease"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          latest_tag: "v2.0.0-moreactions.0"
          last_release: "v1.4.0"
      - id: t1_3
        name: "1.3 Test major version bump without latest_tag as a prerelease"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          last_release: "v1.4.0"
      - id: t1_4
        name: "1.4 Test major version bump without latest_tag as a release"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease_suffix: "moreactions"
          last_release: "v1.4.0"
      - id: t1_5
        name: "1.5 Test major version from empty"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease_suffix: "moreactions"
      - id: test_results
        name: Test results
        run: |
          t1_1="v2.0.0-moreactions.0"
          t1_2="2.0.0-moreactions.1"
          t1_3="2.0.0-moreactions.0"
          t1_4="2.0.0"
          t1_5="1.0.0"
          
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| 1. | ${t1_1} | ${{steps.t1_1.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 2. | ${t1_2} | ${{steps.t1_2.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 3. | ${t1_3} | ${{steps.t1_3.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 4. | ${t1_4} | ${{steps.t1_4.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 5. | ${t1_5} | ${{steps.t1_5.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          
          if [ "${{steps.t1_1.outputs.latest}}" != "${t1_1}" ]; then
            echo "test 1.1 failed"
            exit 1
          fi
          if [ "${{steps.t1_2.outputs.latest}}" != "${t1_2}" ]; then
            echo "test 1.2 failed"
            exit 1
          fi
          if [ "${{steps.t1_3.outputs.latest}}" != "${t1_3}" ]; then
            echo "test 1.3 failed"
            exit 1
          fi
          if [ "${{steps.t1_4.outputs.latest}}" != "${t1_4}" ]; then
            echo "test 1.4 failed"
            exit 1
          fi
          if [ "${{steps.t1_4.outputs.latest}}" != "${t1_4}" ]; then
            echo "test 1.5 failed"
            exit 1
          fi
          

          
