name: "[Test] branch-name"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test_script:
    runs-on: 'ubuntu-latest'
    name: "Test create-tag"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Setup pip"
        run: |
          pip install -q -r ./requirements.txt
      - name: "Setup and run pytest"
        shell: bash
        env:
          RUN_AS_TEST: "true"
        run: |
          cd .github/actions/create-tag/
          pytest ./test_create_tag.py
          echo "$(cat ./results.md)" >> $GITHUB_STEP_SUMMARY
