name: "[Test] terraform-version"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test terraform-version"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test exact value"
        uses: './.github/actions/terraform-version'
        with:
          terraform_directory: "./.github/actions/terraform-version/tests"
          terraform_versions_file: "./one"
      
