name: "[Test] latest-tag"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test latest-tag.py"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test moreactions is found"
        env:
          RUN_AS_TEST: true
        run: |
          src="${{github.action_path}}"
          cd ${src}
          python ./latest-tag.py \
            --test_file=./tests/tags.txt \
            --prerelease=true \
            --prerelease_suffix=moreactions

      # - id: test_results
      #   name: Test results
      #   run: |
      #     t1=""
      #     echo "### Test Information" >> $GITHUB_STEP_SUMMARY
      #     echo "| \# | Branch | Tag | New Tag | " >> $GITHUB_STEP_SUMMARY
      #     echo "| --- | --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
      #     echo "| 1. | ${{steps.test1.outputs.branch_name}} | ${{steps.test1.outputs.tag}} | ${{steps.test1.outputs.new_tag}} |" >> $GITHUB_STEP_SUMMARY

          
