name: "[TEST] Go code"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read


jobs:
  test_go_code:
    name: "Run Go Tests"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          fetch-tags: true
      # setup the go version and pull from cache etc
      - name: "Setup go"
        id: setup_go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          cache: false
          go-version-file: './go.mod'
      # run tests
      - name: "Run tests"
        id: run_tests
        shell: bash
        run: |
          go mod tidy
          go test -count=1 -cover -covermode=atomic ./...
