name: "[Test] safe-strings"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test safe-strings"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - run: |
          ls -l
          ls -l ./.github
          ls -l ./.github/actions
      - id: test1
        name: "Test clean"
        uses: './.github/actions/safe-strings'
        with:
          original: "bot/likes/slashes-and-dashes"
      - id: test2
        name: "Test trim"
        uses: './.github/actions/safe-strings'
        with:
          original: "a-very-very-very-very-long-string-that-should-not-be-used"
          length: 5
      - id: test3
        name: "Test suffix"
        uses: './.github/actions/safe-strings'
        with:
          original: "branch"
          suffix: "1"
      - id: test4
        name: "Test trim and suffix"
        uses: './.github/actions/safe-strings'
        with:
          original: "branchname-to-shortern"
          length: 7
          suffix: "1"
      - id: test5
        name: "Test conditional overwite"
        uses: './.github/actions/safe-strings'
        with:
          original: "main"
          conditional_match: "main"
          conditional_value: "production"
      - id: results
        name: Test results
        run: |
          t1="botlikesslashesanddashes"
          t2="avery"
          t3="branch1"
          t4="branch1"
          t5="production"
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| Test | Expected | Actual |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| One | ${t1} | ${{steps.test1.outputs.safe}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Two | ${t2} | ${{steps.test2.outputs.safe}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Three | ${t3} | ${{steps.test3.outputs.safe}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Four | ${t4} | ${{steps.test4.outputs.safe}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Five | ${t5} | ${{steps.test5.outputs.safe}} |" >> $GITHUB_STEP_SUMMARY

          if [ "${{steps.test1.outputs.safe}}" != "${t1}" ]; then
            exit 1
          fi
          if [ "${{steps.test2.outputs.safe}}" != "${t2}" ]; then
            exit 1
          fi
          if [ "${{steps.test3.outputs.safe}}" != "${t3}" ]; then
            exit 1
          fi
          if [ "${{steps.test4.outputs.safe}}" != "${t4}" ]; then
            exit 1
          fi
          if [ "${{steps.test5.outputs.safe}}" != "${t5}" ]; then
            exit 1
          fi
      
