name: "[Test] latest-tag"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test latest-tag"
    steps:
      - 
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test moreactions is found"
        uses: './.github/actions/latest-tag'
        with: 
          test: true
          branch: "more-actions"
          prerelease: true
          prerelease_suffix: "moreactions"
      - id: test2
        name: "2. Test 123rand123 is not found and latest is empty"
        uses: './.github/actions/latest-tag'
        with: 
          test: true
          branch: "more-actions"
          prerelease: true
          prerelease_suffix: "123rand123"
      - id: test3
        name: "3. Test last release version is 1.4.0"
        uses: './.github/actions/latest-tag'
        with:           
          test: true
      - id: test4
        name: "4. Test branch that matches a release branch forces a release version"
        uses: './.github/actions/latest-tag'
        with: 
          test: true
          branch: "main"
          release_branches: "main"
          prerelease: true
          prerelease_suffix: "123rand123"

      - id: test_results
        name: Test results
        run: |
          t1="v1.5.0-moreactions.0"
          t2=""
          t3="v1.4.0"
          t4="v1.4.0"
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| 1. | ${t1} | ${{steps.test1.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 2. | ${t2} | ${{steps.test2.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 3. | ${t3} | ${{steps.test3.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 4. | ${t4} | ${{steps.test4.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY

          if [ "${{steps.test1.outputs.latest}}" != "${t1}" ]; then
            echo "test 1 failed"
            exit 1
          fi
          if [ "${{steps.test2.outputs.latest}}" != "${t2}" ]; then
            echo "test 2 failed"
            exit 1
          fi
          if [ "${{steps.test3.outputs.latest}}" != "${t3}" ]; then
            echo "test 3 failed"
            exit 1
          fi
          if [ "${{steps.test4.outputs.latest}}" != "${t4}" ]; then
            echo "test 4 failed"
            exit 1
          fi

          
