name: "[Test] next-tag"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test_script:
    runs-on: 'ubuntu-latest'
    name: "Test next-tag [shell test]"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: "Test shell"        
        shell: bash
        env:
          RUN_AS_TEST: "true"
        run: |
          cd .github/actions/next-tag/
          ./run-tests.sh >> $GITHUB_STEP_SUMMARY

  patch:
    runs-on: 'ubuntu-latest'
    name: "Test next-tag [patch]"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test patch version bump as an prerelease without latest_tag"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/patch.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          last_release: "v1.4.0"
          default_bump: "patch"
      - id: test2
        name: "2. Test patch version bump with existing tag"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/patch.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          latest_tag: "v1.4.1-moreactions.1"
          last_release: "v1.4.0"
          default_bump: "patch"
      - id: test3
        name: "3. Test patch version bump as a release"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/patch.txt"
          prerelease_suffix: "moreactions"
          latest_tag: "v1.4.1-moreactions.1"
          last_release: "v1.4.0"
          default_bump: "patch"
      - id: test4
        name: "4. Test patch version bump without latest_tag as a release"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/patch.txt"
          prerelease_suffix: "moreactions"
          default_bump: "patch"
      - id: test_results
        name: Test results [patch]        
        run: |
          t1="1.4.1-moreactions.0"
          t2="1.4.1-moreactions.2"
          t3="1.4.1"
          t4="0.0.1"
          
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| 1. | ${t1} | ${{steps.test1.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 2. | ${t2} | ${{steps.test2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 3. | ${t3} | ${{steps.test3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 4. | ${t4} | ${{steps.test4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          
          if [ "${{steps.test1.outputs.next_tag}}" != "${t1}" ]; then
            echo "test 1 failed"
            exit 1
          fi
          if [ "${{steps.test2.outputs.next_tag}}" != "${t2}" ]; then
            echo "test 2 failed"
            exit 1
          fi
          if [ "${{steps.test3.outputs.next_tag}}" != "${t3}" ]; then
            echo "test 3 failed"
            exit 1
          fi
          if [ "${{steps.test4.outputs.next_tag}}" != "${t4}" ]; then
            echo "test 4 failed"
            exit 1
          fi
  
  minors:
    runs-on: 'ubuntu-latest'
    name: "Test next-tag [minors]"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test minor version bump as an existing prerelease"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/minors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          latest_tag: "v1.5.0-moreactions.0"
          last_release: "v1.4.0"
          default_bump: patch
      - id: test2
        name: "2. Test minor version bump prerelease without latest_tag"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/minors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          last_release: "v1.4.0"
          default_bump: patch
      - id: test3
        name: "3. Test minor version bump as a release"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/minors.txt"
          prerelease_suffix: "moreactions"
          latest_tag: "v1.5.0-moreactions.0"
          last_release: "v1.4.0"
          default_bump: patch
      - id: test4
        name: "4. Test minor version bump without latest_tag as a release"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/minors.txt"
          prerelease_suffix: "moreactions"
          default_bump: patch
      - id: test_results
        name: Test results [Minors]
        run: |
          t1="1.5.0-moreactions.1"
          t2="1.5.0-moreactions.0"
          t3="1.5.0"
          t4="0.1.0"
          
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| 1. | ${t1} | ${{steps.test1.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 2. | ${t2} | ${{steps.test2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 3. | ${t3} | ${{steps.test3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 4. | ${t4} | ${{steps.test4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          
          if [ "${{steps.test1.outputs.next_tag}}" != "${t1}" ]; then
            echo "test 1 failed"
            exit 1
          fi
          if [ "${{steps.test2.outputs.next_tag}}" != "${t2}" ]; then
            echo "test 2 failed"
            exit 1
          fi
          if [ "${{steps.test3.outputs.next_tag}}" != "${t3}" ]; then
            echo "test 3 failed"
            exit 1
          fi
          if [ "${{steps.test4.outputs.next_tag}}" != "${t4}" ]; then
            echo "test 4 failed"
            exit 1
          fi
          
  majors:
    runs-on: 'ubuntu-latest'
    name: "Test next-tag [majors]"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test major version bump as a new prerelease (with v)"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          latest_tag: "v1.5.0-moreactions.1"
          last_release: "v1.4.0"
          with_v: true
          default_bump: patch
      - id: test2
        name: "2. Test major version bump as an existing prerelease"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          latest_tag: "v2.0.0-moreactions.0"
          last_release: "v1.4.0"
          default_bump: patch
      - id: test3
        name: "3. Test major version bump without latest_tag as a prerelease"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease: true
          prerelease_suffix: "moreactions"
          last_release: "v1.4.0"
          default_bump: patch
      - id: test4
        name: "4. Test major version bump without latest_tag as a release"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease_suffix: "moreactions"
          last_release: "v1.4.0"
          default_bump: patch
      - id: test5
        name: "5. Test major version from empty"
        uses: './.github/actions/next-tag'
        with: 
          test: true
          test_file: "./tests/majors.txt"
          prerelease_suffix: "moreactions"
          default_bump: patch
      - id: test_results
        name: Test results [Major]
        run: |
          t1="v2.0.0-moreactions.0"
          t2="2.0.0-moreactions.1"
          t3="2.0.0-moreactions.0"
          t4="2.0.0"
          t5="1.0.0"
          
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| 1. | ${t1} | ${{steps.test1.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 2. | ${t2} | ${{steps.test2.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 3. | ${t3} | ${{steps.test3.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 4. | ${t4} | ${{steps.test4.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 5. | ${t5} | ${{steps.test5.outputs.next_tag}} | " >> $GITHUB_STEP_SUMMARY
          
          if [ "${{steps.test1.outputs.next_tag}}" != "${t1}" ]; then
            echo "test 1 failed"
            exit 1
          fi
          if [ "${{steps.test2.outputs.next_tag}}" != "${t2}" ]; then
            echo "test 2 failed"
            exit 1
          fi
          if [ "${{steps.test3.outputs.next_tag}}" != "${t3}" ]; then
            echo "test 3 failed"
            exit 1
          fi
          if [ "${{steps.test4.outputs.next_tag}}" != "${t4}" ]; then
            echo "test 4 failed"
            exit 1
          fi
          if [ "${{steps.test5.outputs.next_tag}}" != "${t5}" ]; then
            echo "test 5 failed"
            exit 1
          fi
          

          
