name: "[Test] safe-strings"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test safe-strings"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "Test clean"
        uses: './.github/actions/safe-string'
        with:
          original: "bot/likes/slashes-and-dashes?"
      - id: test2
        name: "Test trim"
        uses: './.github/actions/safe-string'
        with:
          original: "a-very-very-very-very-long-string-that-should-not-be-used"
          length: 6
      - id: test3
        name: "Test suffix"
        uses: './.github/actions/safe-string'
        with:
          original: "branch"
          suffix: "1"
      - id: test4
        name: "Test trim and suffix"
        uses: './.github/actions/safe-string'
        with:
          original: "branchname-to-shortern"
          length: 7
          suffix: "1"
      - id: results
        name: Test results
        run: |
          t1="botlikesslashesanddashes"
          t2="a-very"
          t3="branch1"
          t4="branch1"
          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| Test | Expected | Actual |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| One | ${t1} | ${{steps.test1.outputs.version}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Two | ${t2} | ${{steps.test2.outputs.version}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Three | ${t3} | ${{steps.test3.outputs.version}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Four | ${t4} | ${{steps.test4.outputs.version}} |" >> $GITHUB_STEP_SUMMARY

          if [ "${{steps.test1.outputs.version}}" != "${t1}" ]; then
            exit 1
          fi
          if [ "${{steps.test2.outputs.version}}" != "${t2}" ]; then
            exit 1
          fi
          if [ "${{steps.test3.outputs.version}}" != "${t3}" ]; then
            exit 1
          fi
          if [ "${{steps.test4.outputs.version}}" != "${t4}" ]; then
            exit 1
          fi
      
