name: "[Test] branch-name"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test_script:
    runs-on: 'ubuntu-latest'
    name: "Test create-tag"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Setup and run pytest"        
        shell: bash
        env:
          RUN_AS_TEST: "true"
        run: |
          pip3 install git+https://github.com/python-semver/python-semver.git@3.0.2 -q -q
          pip3 install git+https://github.com//gitpython-developers/GitPython.git@3.1.40  -q -q
          pip3 install git+https://github.com//SethMMorton/natsort@8.4.0 -q -q
          pip3 install git+https://github.com/pytest-dev/pytest@6.2.5 -q -q
          cd .github/actions/create-tag/          
          pytest ./test_create_tag.py
          echo "$(cat ./results.md)" >> $GITHUB_STEP_SUMMARY