name: "[Test] branch-name"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test create-tag"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - id: test1
        name: "1. Test a known ref that should return a preexisting semver tag"
        uses: './.github/actions/create-tag'
        with:
          dry_run: true
          commitish: "dab1b63"
          tag_name: "test_tag_wont_be_latest"
      - id: test_results
        name: Test results
        run: |
          t1a="v1.4.0"
          t1b="test_tag_wont_be_latest"

          echo "### Test Information" >> $GITHUB_STEP_SUMMARY
          echo "| \# | Expected | Actual | " >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| 1a. | ${t1a} | ${{steps.test1.outputs.latest}} | " >> $GITHUB_STEP_SUMMARY
          echo "| 1b. | ${t1b} | ${{steps.test1.outputs.created}} | " >> $GITHUB_STEP_SUMMARY
          
          if [ "${{steps.test1.outputs.latest}}" != "${t1a}" ]; then
            echo "test 1a failed"
            exit 1
          fi
          if [ "${{steps.test1.outputs.created}}" != "${t1b}" ]; then
            echo "test 1b failed"
            exit 1
          fi