name: "[Test] safe-strings"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: none
  pull-requests: none
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test safe-strings"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: "Setup pip"
        run: |
          pip install -q -r ./requirements.txt
      - name: "Setup and run pytest"
        shell: bash
        env:
          RUN_AS_TEST: "true"
        run: |
          cd .github/actions/safe-strings/
          pytest ./test_safe_strings.py
          echo "$(cat ./results.md)" >> $GITHUB_STEP_SUMMARY
