name: "[Workflow] TEST GITHUB ACTION"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write


jobs:
  test_action_values:
    name: "TEST GitHub Action ENV"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # run action to test github.actions_x properties
      - name: "Local"
        id: "local_action"
        uses: ./actions/test-gha

  test_branch_name_from_env:
    name: "TEST Branch Name from env"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # run the branch-name action from env values
      - name: "Branch Name"
        id: "branchname"
        uses: ./actions/branch-name
      # summary
      - name: "Summary"
        run: |
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| branch_name | ${{ steps.branchname.outputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| full_length | ${{ steps.branchname.outputs.full_length }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| safe | ${{ steps.branchname.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY

  test_branch_name_fixed:
    name: "TEST Branch Name with fixed input"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # run the branch-name action from env values
      - name: "Branch Name"
        id: "branchname"
        uses: ./actions/branch-name
        with:
          name: "test !/branch name thats really long and has odd things in &!@£$"
      # summary
      - name: "Summary"
        run: |
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| branch_name | ${{ steps.branchname.outputs.branch_name }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| full_length | ${{ steps.branchname.outputs.full_length }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| safe | ${{ steps.branchname.outputs.safe }} |"  >> $GITHUB_STEP_SUMMARY

  end:
    name: 'End'
    runs-on: 'ubuntu-latest'
    needs:
      - test_action_values
      - test_branch_name_from_env
      - test_branch_name_fixed
    steps:
      - name: "End"
        id: end
        run: echo "End"
