name: "[Workflow] Path to Live"

on:
  push:
    branches:
      - main
    paths-ignore:
      - terraform/**
      - .github/workflows/workflow_terraform.yml

permissions:
  actions: read
  contents: write
  id-token: write

env:
  PRERELEASE: "false"
  PATH_TO_LIVE: "true"

# jobs
jobs:
# run tests for hte public github actions
  tests_gha:
    name: "Test public actions"
    uses: './.github/workflows/test_public_github_actions.yml'
    secrets: inherit

  # run tests for the go code base
  tests_go:
    name: "Test go"
    uses: './.github/workflows/test_go.yml'
    secrets: inherit

  # setup provides all vars used in the workflow to make it easier
  setup:
    name: "Set variables"
    needs:
      - tests_go
      - tests_gha
    runs-on: ubuntu-latest
    outputs:
      git_sha: ${{ steps.revhead.outputs.gitsha}}
      # SEMVER & BRANCH NAMES
      semver_tag: ${{ steps.semver_tag.outputs.created_tag }}
    steps:
      # Check the code base
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # generate semver
      # TODO: This is using an older version of self,
      - name: "Generate semver tag and release"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@c9c5dfb290b8f614df0884928c521165ba83d630 # v3.1.4
        with:
          prerelease: ${{ env.PRERELEASE }}
          releases_enabled: false
          with_v: true
      # get the git sha
      - name: "Get git sha"
        id: revhead
        run: |
          sha=$(git rev-parse HEAD)
          echo "gitsha=${sha}" >> $GITHUB_OUTPUT


  # create a release
  release:
    name: "Create release"
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # create a release
      - name: "Create release [${{ needs.setup.outputs.semver_tag }}]"
        id: create
        env:
          GH_TOKEN: ${{ github.token }}
          pre: ${{ env.PRERELEASE == 'true' && '--prerelease' || '' }}
          latest:  ${{ env.PATH_TO_LIVE == 'true' && '--latest=true' || '--latest=false' }}
          tag: ${{ needs.setup.outputs.semver_tag }}
        run: |
          echo "Creating release ... ${{ env.tag }}"
          gh release create ${{ env.tag }} \
            ${{ env.pre }} ${{ env.latest }} --verify-tag \
            -t ${{ env.tag }} \
            --notes-from-tag

  # final step
  end:
    name: 'End'
    runs-on: 'ubuntu-latest'
    needs:
      - release
    steps:
      - id: end
        name: End
        run: echo "End"
