name: "[Workflow] TEST GITHUB ACTION"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write


jobs:
  test_uses:
    name: "TEST GitHub Action"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # pull in local version
      - id: "local_action"
        name: "Local"
        uses: ./.github/actions/test-action
