name: "[Workflow] Path to Live"

on:
  push:
    branches:
      - main
    paths-ignore:
      - terraform/**
      - .github/workflows/workflow_terraform.yml

permissions:
  actions: read
  contents: write
  id-token: write

env:
  PRERELEASE: "false"
  PATH_TO_LIVE: "true"

# jobs
jobs:
  env_values:
    runs-on: ubuntu-latest
    name: "ENV values"
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: "env values"
        uses: ./actions/test-env
# run tests for hte public github actions
  tests_gha:
    name: "Test public actions"
    uses: './.github/workflows/test_public_github_actions.yml'
    secrets: inherit

  # run tests for the go code base
  tests_go:
    name: "Test go"
    uses: './.github/workflows/test_go.yml'
    secrets: inherit

  # setup provides all vars used in the workflow to make it easier
  setup:
    name: "Set variables"
    needs:
      - env_values
      - tests_go
      - tests_gha
    runs-on: ubuntu-latest
    outputs:
      git_sha: ${{ steps.revhead.outputs.gitsha}}
      # SEMVER & BRANCH NAMES
      semver_tag: ${{ steps.semver_tag.outputs.tag }}
    steps:
      # Check the code base
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          fetch-tags: true
      # generate semver - using own version of semver tag!
      - name: "Generate semver tag and release"
        id: semver_tag
        uses: ./actions/semver
        with:
          prerelease: ${{ env.PRERELEASE }}
          create_release: false
      # get the git sha
      - name: "Get git sha"
        id: revhead
        run: |
          sha=$(git rev-parse HEAD)
          echo "gitsha=${sha}" >> $GITHUB_OUTPUT


  # create a release
  release:
    name: "Create release"
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          fetch-tags: true
      # create a release
      - name: "Create release [${{ needs.setup.outputs.semver_tag }}]"
        id: create_release
        uses: ./actions/release
        with:
          tag: ${{ needs.setup.outputs.semver_tag }}
          prerelease: ${{ env.PRERELEASE }}
          latest: true
          github_token: ${{ github.token }}

  # final step
  end:
    name: 'End'
    runs-on: 'ubuntu-latest'
    needs:
      - release
    steps:
      - id: end
        name: End
        run: echo "End"
