name: "[Workflow] Test GitHub environment values"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write

jobs:
  # testing what github.actions_x properties are
  test_action_values:
    name: "TEST GitHub Action ENV"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # run action to test github.actions_x properties
      - name: "Local"
        id: "local_action"
        uses: ./actions/test-gha

  # final step
  end:
    name: 'End'
    runs-on: 'ubuntu-latest'
    needs:
      - test_action_values
    steps:
      - id: end
        name: End
        run: echo "End"
